### PR TITLE
Always deal with arrays of element at the middleware level

### PR DESCRIPTION
**Pull request by geowarin**
Hi there!
Sorry, my first pull request is kind of a breaking change.

This pull requests makes the API more uniform by always feeding an array of elements to the 
middlewares.
Previously, elements could be either an array or a single element which forces
middleware authors to handle both cases.

For the users, when calling the test() method, helpers.elements will always contain arrays.
However, they can still benefit from the shortcut syntax test({myElement}).
In that case, elements will be 'unnaraid', which means that that they can either get an array
of elements or a single element depending on their component layout.

What do you think?

### CODE REVIEW

**Comment by zackify** [comment]
I'm curious what @kenwheeler and @dphaener thinks of this. I'm not sure if I think this is necessary. But I'm not against it.

**Comment by kenwheeler** [comment]
I'm not sure I'd want to implicitly click every match, as shown in the new simulate syntax. I would much rather add middleware for dealing with arrays such as `each()` or `index()`

**Comment by geowarin** [comment]
I find it tiresome to write the same ceremonial over and over:

Middleware operating on a single element:
    let element = this.helpers.elements[data.element];
    element = Array.isArray(element) ? element[0] : element;

Middleware operating on a collection
    let elements = this.helpers.elements[data.elements];
    elements = Array.isArray(elements) ? elements : [element];

@kenwheeler This sounds like an interesting idea! Could you show an example of what the syntax would look like?

**Comment by geowarin** [comment]
Another argument to back up my idea.
Imagine you are testing if your component can render a list of elements:

        Test(<AlertsView />)
        .setState({alerts})
        .find('.collection-item')
        .test(({helpers}) => {
          expect(helpers.elements['collection-item'].length).equal(2)
        })

If you test with a single element, you cannot write the following:

      .test(({helpers}) => {
          expect(helpers.elements['collection-item'].length).equal(1)
        })

**Pull request closed without merging**
