### PR TITLE
Adding `Simulate` middleware

### PR DESCRIPTION
**Pull request by kenwheeler**
Added Simulate middleware

Use:

```
let spy = sinon.spy();

Test(<TestComponent onClick={spy}/>)
    .use(Find, 'button')
    .use(Simulate, {method: 'click', element: 'button'})
    .test(function() {
      expect(spy.called).to.be.true;
    })
```

### CODE REVIEW

**Comment by kenwheeler** [comment]
It takes an object of options:

*method* - string, required - The Simulate method to get called (ex: keyDown, click)
*element* - string, optional - The element from `this.helpers.elements` to click. Defaults to the component itself.
*options* - object, optional - The options object to provide to the Simulate method for things like `keyCode`

**Comment by luisrudge** [comment]
Awesome!

**Comment by zackify** [comment]
Beautiful! Add it to the list of middleware :D https://github.com/Legitcode/tests/wiki/Middleware

**Comment by luisrudge** [comment]
Please add to readme as well

**Comment by zackify** [comment]
@luisrudge I added it to the main example, won't always be able to do that since it'll get too big. That's what the other page is for

**Pull request merged**
