### PR TITLE
added .element

### PR DESCRIPTION
**Pull request by zackify**
implements #16

### CODE REVIEW

**Comment by zackify** [comment]
Thoughts? @kenwheeler @dphaener

**Comment by geowarin** [comment]
I think it's a better API than #9 because it is more declarative.
Maybe having a syntax like:

    .element('box', box => {
      expect(box.props.children).to.be.equal('found me!')
    })

would completely remove the need for #9 and make it more flexible (the findFirst choice makes the API more difficult to undestand)

**Comment by JedWatson** [comment]
+1

**Comment by zackify** [comment]
@geowarin how about we use your syntax, if the first argument isn't passed, it defaults to the first element! :) good idea

**Pull request merged**
