### PR TITLE
Add component to 'this' for mixins

### PR DESCRIPTION
**Pull request by NickStefan**
add component to 'this' on line 21:
```
const testComponent = {
    instance,
    component,
```

I'd like to be able to write mixins that make use of the component instance, rather than the rendered instance:

mixin I'd use:
```
function testMethod(methodName, fn){
    var bound = _.bind(this.component.type.prototype[methodName], this.component);
    fn(bound);
}

function Test(component, options={}){
    return TestUtils(component, options)
    .mixin({
        testMethod
    });
}

      it('should have a working bob method', function(){
            Test(<ComponentText data={data}/>, {shallow: true})
            .testMethod('bob', function(bob){
                expect(bob('hi')).to.equal('hi');
            });
        });
```

### CODE REVIEW

**Comment by zackify** [comment]
Thanks! I'll publish in a little bit.

**Comment by zackify** [comment]
@NickStefan published :)

**Comment by NickStefan** [comment]
thanks for the quick publish. i love this library. it reads like a web driver test, but without all of the pain of selenium.

**Comment by zackify** [comment]
@NickStefan thanks :) so glad people like it!

**Pull request merged**
